Home work24.1
KostiantynVorobiov/My-own-project-Internet-shop- pull request #1
Opened 2020-09-03 11:06 UTC by KostiantynVorobiov

2020-09-03 12:32 UTC, vremere-a approved these changes

2020-09-03 12:32 UTC, vremere-a commented on src/main/java/com/internet/shop/models/Product.java
> +    private Double price;
for advise - use BigDecimal.

2020-09-03 14:04 UTC, KseniiaMakarova requested changes
also, remove `<dependencies>` block from pom.xml
we do not use dependencies yet

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        Product fistProduct = new Product("Samsung", 7000.55);
let's use more informative names like `motorola`, `samsung`

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println("Read product by ID " + productService.get(3L));
save your products to variables and use something like `huawei.getId()` instead where needed

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return Optional.empty();
let's use Stream API and `findFirst()`

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        }
the logic is ok, but let's use Stream API

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return true;
you can use `removeIf()` on storage

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/models/Order.java
> +        this.userId = userId;
we will not receive `products` from outside

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/models/Product.java
> +    private Double price;
```suggestion
    private double price;
```
using a wrapper is recommended for id, but for this field we can use a primitive type

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/models/ShoppingCart.java
> +        this.products = products;
same: we will not receive products from outside

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/models/User.java
> +package com.internet.shop.models;
```suggestion
package com.internet.shop.model;
```

let's name packages in singular

2020-09-03 14:04 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.getById(id).orElseThrow();
```suggestion
        return productDao.getById(id).get();
```
let's use `get()` for now

2020-09-03 14:12 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/Application.java
> +        Product fistProduct = new Product("Samsung", 7000.55);
Done

2020-09-03 14:20 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/Application.java
> +        System.out.println("Read product by ID " + productService.get(3L));
Done

2020-09-03 14:22 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/models/Order.java
> +        this.userId = userId;
Done

2020-09-03 14:23 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/models/Product.java
> +    private Double price;
Done

2020-09-03 14:24 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/models/User.java
> +package com.internet.shop.models;
Done

2020-09-03 14:26 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/models/ShoppingCart.java
> +        this.products = products;
Done

2020-09-03 14:26 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/service/impl/ProductServiceImpl.java
> +        return productDao.getById(id).orElseThrow();
Done

2020-09-03 15:34 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return true;
Done

2020-09-03 15:35 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        return Optional.empty();
Done

2020-09-03 15:48 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +        }
Done

2020-09-03 16:17 UTC, KseniiaMakarova requested changes

2020-09-03 16:17 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .filter(product -> product.getId() == id)
how do we compare object types?

2020-09-03 16:17 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +    public Order(List<Product> products, Long userId) {
```suggestion
    public Order(Long userId) {
```

2020-09-03 16:17 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +    public ShoppingCart(List<Product> products, Long userId) {
same here

2020-09-04 06:13 UTC, KseniiaMakarova approved these changes

2020-09-04 06:57 UTC, merged