Home w33
KostiantynVorobiov/My-own-project-Internet-shop- pull request #10
Opened 2020-09-24 14:44 UTC by KostiantynVorobiov

2020-09-24 16:43 UTC, vremere-a approved these changes
good job

2020-09-24 16:43 UTC, vremere-a commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                return Optional.of(order);
colleagues advise to use ofNulable ()
because if wrong order came - you might get npe...

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/Application.java
>  public class Application {
цей клас уже можна видаляти

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orderList.add(getOrderFromResultSet(resultSet));
тут ми викликаємо метод getOrderFromResultSet в якому знову відкривається connection
виходить що в нас в connection відкривається новий connection - а це не ок практика
спробуй позбутись цього у всіх методах де це зустрічається

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                return Optional.of(order);
@vremere-a в даному випадку не може виникнути помилки, можна залишити як є

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            return preparedStatement.executeUpdate() == 1;
краще робити перевірку наступного вигляду:
            return preparedStatement.executeUpdate() > 0;
це стосується всіх решта випадків

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +            Long roleId = null;
краще не повертати null а кидати помилку що такої ролі немає, або ж повертати optional

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        String query = "UPDATE users SET name=?, login=?, password=? "
чи варто оновлювати ролі разом з юзером?

2020-09-25 07:32 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                userRoles.add(Role.of(resultSet.getString("role_name")));
чому ми не витягуємо ід?

2020-09-25 08:06 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/Application.java
>  public class Application {
Done

2020-09-25 08:08 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            return preparedStatement.executeUpdate() == 1;
Done

2020-09-25 08:28 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +        String query = "UPDATE users SET name=?, login=?, password=? "
Done

2020-09-25 13:36 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
> +                userRoles.add(Role.of(resultSet.getString("role_name")));
Done

2020-09-25 14:57 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +                orderList.add(getOrderFromResultSet(resultSet));
Done

2020-09-28 15:55 UTC, KseniiaMakarova requested changes

2020-09-28 15:55 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            }
if we don't need the ResultSet anymore, let's close the statement before we pass the connection to a different methid

2020-09-28 15:55 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            addProductToOrder(order, connection);
same here

2020-09-28 15:55 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            addProductsToShoppingCart(shoppingCart, connection);
same here

2020-09-28 15:55 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            addProductsToShoppingCart(shoppingCart, connection);
and here

2020-09-28 18:03 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            }
Done

2020-09-28 18:04 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/OrderDaoJdbcImpl.java
> +            addProductToOrder(order, connection);
Done

2020-09-28 18:05 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            addProductsToShoppingCart(shoppingCart, connection);
Done

2020-09-28 18:05 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            addProductsToShoppingCart(shoppingCart, connection);
Done

2020-09-29 09:23 UTC, merged